# Generated by Django 3.2.6 on 2021-08-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('female', 'F'), ('male', 'M'), ('others', 'O')], default='F', max_length=20),
        ),
    ]
